In [36]:
import numpy as np

In [37]:
arr = np.array([1,7,13,105])
print(f"Array Size = {arr.size}")

Array Size = 4


In [38]:
arr1= np.array([10,30,50])
arr2 = np.array([20,40,60])

greater = np.greater(arr1,arr2)
print(greater)

equal = np.greater_equal(arr1,arr2)
print(equal)

lesser = np.less(arr1,arr2)
print(lesser)

[False False False]
[False False False]
[ True  True  True]


In [39]:
 
 arr1 = np.zeros(10)
 print(arr1)
 arr2 = np.ones(10)
 print(arr2)
 arr3 = np.full(10,5)
 print(arr3)
 arr4= np.full(10,10)
 print(arr4)
 arr5 = np.full(10,20)
 print(arr5)
 arr6= np.full(10,50)
 print(arr6)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[10 10 10 10 10 10 10 10 10 10]
[20 20 20 20 20 20 20 20 20 20]
[50 50 50 50 50 50 50 50 50 50]


In [40]:
arr1 = np.arange(30,71)
print(arr1)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [41]:
arr1= np.arange(50,96)
print(arr1)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [42]:
arr1 = np.arange(20,82,2)
print(arr1)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80]


In [43]:
arr1 = np.arange(21,81,2)
print(arr1)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [44]:
n3 = np.random.randint(10,40,15)
print(n3)

[10 27 20 16 21 37 19 34 36 39 14 14 32 18 23]


In [45]:
n3 = np.random.randint(30,50,10)
print(n3)

[42 46 46 43 33 41 32 49 44 35]


In [46]:
n3= np.random.randint(50,90,20)
print(n3)

[60 50 64 84 65 88 79 87 77 61 81 55 77 58 60 82 86 67 74 55]


In [47]:
arr1=np.array([10,20,30,40])
arr2=np.array([50,60,70,80])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[ 60  80 100 120]
[-40 -40 -40 -40]
[ 500 1200 2100 3200]
[0.2        0.33333333 0.42857143 0.5       ]


In [48]:
n1 = np.arange(10,22)
n1 = n1.reshape(3,4)
print(n1)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [49]:
n1= np.eye(3)
print(n1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
#Q14
n1 = np.array([[10,20,30],[40,50,60],[70,80,90]])

num_rows = n1.shape[0]
num_columns= n1.shape[1]
print(num_rows)
print(num_columns)

3
3


In [51]:
#Q.15

print(np.diag([1,2,3,4,5]))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [52]:
#Q.16
array3d = np.random.randint(1,11, size= (3,3,3))
print(array3d)

[[[9 4 8]
  [3 1 8]
  [2 4 9]]

 [[8 5 4]
  [8 9 3]
  [1 6 9]]

 [[7 9 5]
  [4 6 8]
  [9 2 9]]]


In [53]:
array2_3_4d = np.random.randint(1,11, size = (2,3,4))
print(array2_3_4d)

[[[ 6  2  1  8]
  [10  9  2  7]
  [ 7  3  3  8]]

 [[ 7  9  9 10]
  [ 5  8  6  7]
  [ 8 10  1  9]]]


In [54]:
#Q.18
ls = ([10,20,30,40,50])
print(np.array(ls))

[10 20 30 40 50]


In [55]:
#Q.19
array3_3d = np.random.randint(2,11, size= (3,3,3))
print(array3_3d)

[[[7 7 3]
  [5 8 6]
  [7 3 5]]

 [[8 4 5]
  [6 9 9]
  [3 2 6]]

 [[4 4 3]
  [5 6 6]
  [8 6 4]]]


In [56]:
#Q.20
arr = np.arange(12,38)
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [57]:
#Q.21
arr = np.arange(12,38)
reverse = np.flip(arr)
print(reverse)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [58]:
n1 = 20
print(float(n1))

20.0


In [59]:
n1= ([10,20,30,40])
print(np.array(n1))

[10 20 30 40]


In [60]:
arr1 = ([10,20,30,40])
arr2 = ([50,60,70,80])
remainder = np.mod(arr1,arr2)
print(remainder)

[10 20 30 40]


In [62]:
import numpy as np

numbers = np.arange(20, 50)
divisible_by_3 = numbers[numbers % 3 == 0]
remainder = divisible_by_3 % numbers

print("Numbers divisible by 3:")
print(divisible_by_3)
print("\nElement-wise remainder:")
print(remainder)


ValueError: operands could not be broadcast together with shapes (10,) (30,) 